---
# For CML2 only the data dictionary with cml_label, cml_platform
# and cml_position under the hostname is required.
#
# The following is an inventory example to extend a nornir host
# file with the information needed by the cml2_lab_build script.
#
# NXOS-SW-1:
#  hostname: 10.10.100.11
#  username: cisco
#  password: cisco
#  connection_options:
#    netmiko:
#      platform: cisco_nxos_ssh
#    napalm:
#      platform: nxos_ssh
#    netconf:
#      extras:
#        allow_agent: False
#        hostkey_verify: False
#        look_for_keys: False
#  data:
#     cml_label: SW-1
#     cml_platform: iosvl2
#     cml_position: [0, -100]

nxosv9000:
  data:
    cml_label: nxosv9000
    cml_platform: nxosv9000
    cml_position: [0, -300]

nxosv:
  data:
    cml_label: nxosv
    cml_platform: nxosv
    cml_position: [0, -200]

iosvl2:
  data:
    cml_label: iosvl2
    cml_platform: iosvl2
    cml_position: [0, -100]

coreos:
  data:
    cml_label: coreos
    cml_platform: coreos
    cml_position: [100, -200]

alpine:
  data:
    cml_label: alpine
    cml_platform: alpine
    cml_position: [100, -100]

server:
  data:
    cml_label: server
    cml_platform: server
    cml_position: [100, 0]

iosv:
  data:
    cml_label: iosv
    cml_platform: iosv
    cml_position: [0, 0]

iosxrv:
  data:
    cml_label: iosxrv
    cml_platform: iosxrv
    cml_position: [0, 100]

iosxrv9000:
  data:
    cml_label: iosxrv9000
    cml_platform: iosxrv9000
    cml_position: [0, 200]

csr1000v:
  data:
    cml_label: csr1000v
    cml_platform: csr1000v
    cml_position: [0, 300]
