---
# For CML2 only the data dictionary with cml_label, cml_platform
# and cml_position under the hostname is required.
#
# The following is an inventory example to extend a nornir host
# file with the information needed by the cml2_lab_build script.
#
# NXOS-SW-1:
#  hostname: 10.10.100.11
#  username: cisco
#  password: cisco
#  connection_options:
#    netmiko:
#      platform: cisco_nxos_ssh
#    napalm:
#      platform: nxos_ssh
#    netconf:
#      extras:
#        allow_agent: False
#        hostkey_verify: False
#        look_for_keys: False
#  data:
#     cml_label: SW-1
#     cml_platform: iosvl2
#     cml_position: [0, -100]

N9K-01:
  data:
    cml_label: N9K-01
    cml_platform: nxosv9000
    cml_position: [-300, 0]

N9K-02:
  data:
    cml_label: N9K-02
    cml_platform: nxosv9000
    cml_position: [0, -150]

N9K-03:
  data:
    cml_label: N9K-03
    cml_platform: nxosv9000
    cml_position: [0, 150]
