---
# host_a and host_b are the CML2 nodes where a link will be created.
# interface_a and interface_b needs to match exactly with the provided
# config file, as the script will take these interfaces configurations
# and configure the dynamically assigned interfaces by CML2.
# If no configuration is provided, the values of these keys can be blank.
#
# For example:
# - host_a: Hostname-A
#    interface_a: GigabitEthernet1/0/1
#    host_b: Hostname-B
#    interface_b: GigabitEthernet1/0/1
# or
# - host_a: Hostname-A
#    interface_a:
#    host_b: Hostname-B
#    interface_b:

link_list:
  - host_a: nxosv9000
    interface_a:
    host_b: nxosv
    interface_b:

  - host_a: iosvl2
    interface_a:
    host_b: iosv
    interface_b:

  - host_a: iosvl2
    interface_a:
    host_b: coreos
    interface_b:

  - host_a: iosvl2
    interface_a:
    host_b: server
    interface_b:

  - host_a: iosvl2
    interface_a:
    host_b: alpine
    interface_b:

  - host_a: iosxrv
    interface_a:
    host_b: iosxrv9000
    interface_b:

  - host_a: csr1000v
    interface_a:
    host_b: iosxrv9000
    interface_b:
